import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "@/components/Nav";
import { geistSans, geistMono } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        <Nav title="Navigation" />
        {children}
      </body>
    </html>
  );
}
